function buildCatalogIndex(programs) {
  const programsByKey = new Map();
  const coursesByKey = new Map();
  const lessonsByKey = new Map();

  programs.forEach((program) => {
    programsByKey.set(program.key, program);

    program.courses.forEach((course) => {
      coursesByKey.set(`${program.key}:${course.key}`, { ...course, programKey: program.key, programTitle: program.title, credential: program.credential });

      course.lessons.forEach((lesson) => {
        lessonsByKey.set(`${program.key}:${course.key}:${lesson.key}`, {
          ...lesson,
          programKey: program.key,
          programTitle: program.title,
          courseKey: course.key,
          courseTitle: course.title,
          credential: program.credential,
        });
      });
    });
  });

  return { programsByKey, coursesByKey, lessonsByKey };
}

export function buildProgramHref(programKey) {
  return `/academy/programs/${programKey}`;
}

export function buildCourseHref(programKey, courseKey) {
  return `/academy/programs/${programKey}/courses/${courseKey}`;
}

export function buildLessonHref(programKey, courseKey, lessonKey) {
  return `/academy/programs/${programKey}/courses/${courseKey}/lessons/${lessonKey}`;
}

const programs = [
  {
    key: "ops-core",
    title: "Construction Operations Foundations",
    credential: "FCA Core Operations Certificate",
    audience: "Owners, operations coordinators, assistant PMs, office leads, and emerging operations managers",
    duration: "12 weeks · 3 graduate-style seminars + applied lab block",
    format: "Faculty-guided seminar, project memo writing, case-method discussion, live workspace labs",
    outcome: "Install disciplined execution habits across intake, qualification, scope transfer, handoff, kickoff, and customer visibility.",
    goal: "Teach learners to govern contractor operations with the precision of a professional graduate program while remaining anchored to live FCA workflows.",
    linkedSurface: "/portal/platform",
    linkedLabel: "Open Platform Dashboard",
    classrooms: ["Construction Operations Foundations"],
    stack: ["Portal workspace", "Bid continuity", "Customer coordination", "Auricrux guidance"],
    outcomes: [
      "Diagnose breakdowns in sales-to-operations handoff before they become cost leakage.",
      "Write executive-grade operating briefs that turn fragmented notes into decision-ready direction.",
      "Establish project kickoff discipline across owner expectations, internal teams, and downstream field control.",
      "Use Auricrux-guided workflow state to preserve continuity across bids, files, messaging, and next actions.",
    ],
    courses: [
      {
        key: "ops-governance",
        code: "OPS 601",
        title: "Operating System Governance for Contractors",
        lessons: 3,
        lab: "Build a governance brief that ties intake facts to project setup controls.",
        summary: "A high-rigor introduction to contractor operating architecture, continuity discipline, and project-state control.",
        linkedSurface: "/portal/platform",
        linkedLabel: "Open Platform Dashboard",
        lessonsData: [
          {
            key: "system-law-and-continuity",
            title: "System Law, Continuity, and the Cost of Fragmentation",
            duration: "95 minutes",
            type: "Seminar",
            objective: "Evaluate why fragmented contractor tools produce operational drift and how unified system law restores disciplined execution.",
            prompt: "Write a comparative memo explaining how disconnected CRM, PM, billing, and training systems create hidden failure points in contractor delivery.",
            assessment: "Executive memo + oral defense",
            linkedSurface: "/portal/platform",
            linkedLabel: "Review live platform posture",
            concepts: ["continuity spine", "artifact rule", "lifecycle state discipline", "founder-hands-off execution"],
            caseStudy: "A regional contractor loses margin because sales notes, drawing revisions, and kickoff assumptions never reconcile into one governed record.",
          },
          {
            key: "handoff-governance",
            title: "Handoff Governance and Operational Baselines",
            duration: "110 minutes",
            type: "Case Lab",
            objective: "Construct a baseline operating packet that can survive handoff from preconstruction to project delivery.",
            prompt: "Using a bid-to-award scenario, define the minimum baseline artifacts required before project mobilization can proceed.",
            assessment: "Baseline packet review",
            linkedSurface: "/portal/projects",
            linkedLabel: "Open Project Flow",
            concepts: ["baseline quality", "decision rights", "project-state validity", "handoff evidence"],
            caseStudy: "A job starts without trade clarifications, creating field confusion, subcontractor claims, and owner distrust.",
          },
          {
            key: "auricrux-executive-ops",
            title: "Auricrux as Executive Operator",
            duration: "90 minutes",
            type: "Applied Discussion",
            objective: "Use the Auricrux control layer to convert observations into bounded decisions, corrective actions, and logged follow-through.",
            prompt: "Produce a next-action ledger for a contractor whose estimating, communications, and kickoff readiness are drifting simultaneously.",
            assessment: "Action ledger + audit review",
            linkedSurface: "/portal/auricrux",
            linkedLabel: "Open Auricrux workspace",
            concepts: ["executive intelligence", "auditability", "bounded escalation", "self-correction"],
            caseStudy: "Commercial urgency collides with weak delivery readiness, requiring structured correction instead of cosmetic motion.",
          },
        ],
      },
      {
        key: "client-execution-discipline",
        code: "OPS 624",
        title: "Client Execution and Delivery Discipline",
        lessons: 3,
        lab: "Run a kickoff, escalation, and close-the-loop client communication sequence.",
        summary: "Trains learners to manage owner-facing continuity with precision, credibility, and documented control.",
        linkedSurface: "/portal/messages",
        linkedLabel: "Open Messages",
        lessonsData: [
          {
            key: "client-trust-architecture",
            title: "Client Trust Architecture",
            duration: "100 minutes",
            type: "Seminar",
            objective: "Design communication standards that make a contractor look controlled, prepared, and professionally accountable.",
            prompt: "Draft a communication architecture for award, kickoff, drawing clarification, and billing confidence moments.",
            assessment: "Trust architecture rubric",
            linkedSurface: "/portal/messages",
            linkedLabel: "Open customer messaging",
            concepts: ["trust surfaces", "response discipline", "expectation setting", "commercial confidence"],
            caseStudy: "An owner perceives chaos because updates are reactive, inconsistent, and disconnected from actual project status.",
          },
          {
            key: "decision-brief-writing",
            title: "Decision Brief Writing for Operations Leaders",
            duration: "85 minutes",
            type: "Writing Lab",
            objective: "Produce concise, high-signal operating briefs that frame issue, risk, fix, and next build step.",
            prompt: "Convert a messy coordination thread into a leadership brief suitable for executive review.",
            assessment: "Brief quality review",
            linkedSurface: "/portal/audit",
            linkedLabel: "Open Audit",
            concepts: ["brief discipline", "decision framing", "operational writing", "signal quality"],
            caseStudy: "A superintendent, PM, and estimator all describe the same problem differently, causing leadership confusion.",
          },
          {
            key: "service-recovery-loop",
            title: "Service Recovery and Corrective Action Loops",
            duration: "105 minutes",
            type: "Simulation",
            objective: "Orchestrate a recovery sequence when client confidence drops, ensuring corrective action is visible and verifiable.",
            prompt: "Respond to a schedule slip and missing documentation complaint with a bounded, trust-preserving recovery loop.",
            assessment: "Simulation scorecard",
            linkedSurface: "/portal/support",
            linkedLabel: "Open Support Continuity",
            concepts: ["service recovery", "escalation design", "corrective sequencing", "commercial preservation"],
            caseStudy: "A customer is ready to freeze approvals because prior promises were not translated into observable execution.",
          },
        ],
      },
    ],
  },
  {
    key: "precon-estimating",
    title: "Estimating and Preconstruction Readiness",
    credential: "Preconstruction Readiness Certificate",
    audience: "Estimators, project executives, procurement leads, and preconstruction managers",
    duration: "10 weeks · estimating studio + vendor strategy clinic",
    format: "Studio critique, pricing workshops, package review boards, scenario drills",
    outcome: "Strengthen scope control, vendor bid handling, pricing accuracy, and award recommendations.",
    goal: "Make preconstruction a disciplined analytic function rather than a spreadsheet scramble.",
    linkedSurface: "/portal/bids",
    linkedLabel: "Open Bid Workspace",
    classrooms: ["Estimating, Bidding, and Margin Control"],
    stack: ["Bid workspace", "Project flow", "Commercial packaging", "Approval routing"],
    outcomes: [
      "Separate scope completeness from price confidence so bids are not mistaken for reliable strategy.",
      "Interrogate vendor quotes for exclusions, schedule assumptions, and hidden commercial traps.",
      "Translate early estimates into award-ready recommendations with clear risk narrative.",
      "Bind preconstruction outputs to downstream project and file continuity.",
    ],
    courses: [
      {
        key: "scope-analysis",
        code: "PRECON 611",
        title: "Scope Analytics and Bid Package Architecture",
        lessons: 3,
        lab: "Develop a bid-leveling memo and scope-gap matrix for a multi-trade package.",
        summary: "Advanced scope reading, package strategy, and structured bid comparison.",
        linkedSurface: "/portal/bids",
        linkedLabel: "Open Bid Workspace",
        lessonsData: [
          {
            key: "scope-reading-rigor",
            title: "Scope Reading Rigor",
            duration: "100 minutes",
            type: "Studio",
            objective: "Interrogate drawings, specifications, and proposal narratives for missing scope and false equivalence across bids.",
            prompt: "Prepare a scope-gap analysis for three subcontractor bids that appear comparable but are not commercially equivalent.",
            assessment: "Scope-gap matrix",
            linkedSurface: "/portal/files",
            linkedLabel: "Open Files Workspace",
            concepts: ["scope completeness", "comparability", "drawing/spec interpretation", "risk flags"],
            caseStudy: "The low bidder excluded temporary protection, phasing burdens, and final commissioning support.",
          },
          {
            key: "vendor-leveling-board",
            title: "Vendor Leveling Board",
            duration: "115 minutes",
            type: "Board Review",
            objective: "Build a leveling framework that surfaces exclusions, qualifications, capacity issues, and pricing anomalies.",
            prompt: "Lead a mock leveling board and recommend the most reliable award path.",
            assessment: "Award recommendation memo",
            linkedSurface: "/portal/proposals",
            linkedLabel: "Open Proposals",
            concepts: ["leveling", "commercial reasoning", "capacity risk", "award posture"],
            caseStudy: "The apparent second-high bidder is the only vendor with credible manpower and sequencing capacity.",
          },
          {
            key: "margin-defense",
            title: "Margin Defense and Commercial Integrity",
            duration: "95 minutes",
            type: "Seminar",
            objective: "Defend margin without confusing markup discipline with arbitrary price inflation.",
            prompt: "Explain how contingency, overhead, escalation, and execution risk should appear in a credible estimate narrative.",
            assessment: "Commercial integrity memo",
            linkedSurface: "/portal/estimates",
            linkedLabel: "Open Estimates",
            concepts: ["margin architecture", "contingency", "risk pricing", "commercial communication"],
            caseStudy: "Leadership pressures the team to cut price without understanding which assumptions are protecting delivery viability.",
          },
        ],
      },
      {
        key: "proposal-strategy",
        code: "PRECON 645",
        title: "Proposal Strategy and Award Positioning",
        lessons: 3,
        lab: "Create a client-facing proposal package with alternates, clarifications, and award posture.",
        summary: "Connects estimating outputs to persuasive, risk-aware commercial packaging.",
        linkedSurface: "/portal/proposals",
        linkedLabel: "Open Proposals",
        lessonsData: [
          {
            key: "proposal-architecture",
            title: "Proposal Architecture for High-Trust Awards",
            duration: "90 minutes",
            type: "Seminar",
            objective: "Structure proposals so owners can understand scope, assumptions, options, and risk boundaries without ambiguity.",
            prompt: "Build a proposal outline that clearly distinguishes base scope, exclusions, alternates, and decision deadlines.",
            assessment: "Proposal architecture review",
            linkedSurface: "/portal/proposals",
            linkedLabel: "Open Proposals",
            concepts: ["proposal structure", "clarity", "decision support", "risk framing"],
            caseStudy: "A client rejects a proposal because the estimate looked padded when the real issue was poor explanation.",
          },
          {
            key: "award-interview",
            title: "Award Interview and Executive Defense",
            duration: "85 minutes",
            type: "Simulation",
            objective: "Defend pricing, schedule posture, and contractor readiness under client scrutiny.",
            prompt: "Present an award defense to an owner panel challenging your assumptions, manpower plan, and fee structure.",
            assessment: "Panel simulation score",
            linkedSurface: "/portal/platform",
            linkedLabel: "Open Platform Dashboard",
            concepts: ["executive defense", "award credibility", "schedule reasoning", "client psychology"],
            caseStudy: "The owner believes all bidders are interchangeable and wants proof that execution strength justifies selection.",
          },
          {
            key: "handoff-precon-to-project",
            title: "Preconstruction-to-Project Handoff",
            duration: "105 minutes",
            type: "Applied Lab",
            objective: "Translate winning bid assumptions into project startup artifacts the delivery team can actually use.",
            prompt: "Produce the minimum handoff packet required to preserve preconstruction truth after award.",
            assessment: "Handoff packet audit",
            linkedSurface: "/portal/projects",
            linkedLabel: "Open Project Flow",
            concepts: ["award translation", "handoff discipline", "continuity", "execution readiness"],
            caseStudy: "The PM inherits a profitable bid but cannot see the assumptions that made it viable.",
          },
        ],
      },
    ],
  },
  {
    key: "project-controls",
    title: "Project Controls and Document Governance",
    credential: "Project Controls Certificate",
    audience: "Project managers, coordinators, document control specialists, and QA-focused delivery leaders",
    duration: "11 weeks · technical lab + governance practicum",
    format: "Interactive drawing review, RFI/submittal simulation, revision control lab, closeout archive review",
    outcome: "Make RFIs, submittals, revisions, and closeout packages dependable and audit-ready.",
    goal: "Train document control as a strategic execution function, not clerical overhead.",
    linkedSurface: "/portal/files",
    linkedLabel: "Open Files Workspace",
    classrooms: ["Document Control, RFIs, and Submittals"],
    stack: ["Files workspace", "Messages", "Closeout continuity", "Audit-ready records"],
    outcomes: [
      "Control revision truth so teams do not build from obsolete intent.",
      "Frame RFIs and submittals as decision instruments rather than paperwork churn.",
      "Build closeout packages that protect payment, warranty, and long-term trust.",
      "Preserve auditable document state across file intake, messaging, and operational actions.",
    ],
    courses: [
      {
        key: "document-truth",
        code: "CTRL 631",
        title: "Document Truth and Revision Governance",
        lessons: 3,
        lab: "Audit a drawing set, revision log, and distribution history for governance failure points.",
        summary: "Establishes the intellectual discipline required to keep project documents authoritative.",
        linkedSurface: "/portal/files",
        linkedLabel: "Open Files Workspace",
        lessonsData: [
          {
            key: "revision-authority",
            title: "Revision Authority and File Lineage",
            duration: "100 minutes",
            type: "Technical Lab",
            objective: "Determine which document version is authoritative, who has acted on it, and what downstream decisions depend on it.",
            prompt: "Build a lineage map for a drawing package after multiple addenda and bulletin releases.",
            assessment: "Lineage map review",
            linkedSurface: "/portal/files",
            linkedLabel: "Open Files Workspace",
            concepts: ["file lineage", "authority state", "distribution control", "downstream dependency"],
            caseStudy: "Field crews continue working from superseded details because distribution controls were informal.",
          },
          {
            key: "decision-quality-rfis",
            title: "Decision-Quality RFIs",
            duration: "90 minutes",
            type: "Writing Studio",
            objective: "Write RFIs that isolate genuine ambiguity, frame consequences, and accelerate useful responses.",
            prompt: "Rewrite a vague field question into a decision-grade RFI with sheet references and schedule impact.",
            assessment: "RFI quality rubric",
            linkedSurface: "/portal/messages",
            linkedLabel: "Open Messages",
            concepts: ["question quality", "ambiguity isolation", "schedule consequence", "evidence framing"],
            caseStudy: "The design team rejects an RFI because the contractor never identified the actual conflict or affected scope.",
          },
          {
            key: "submittal-risk-control",
            title: "Submittal Risk Control",
            duration: "105 minutes",
            type: "Simulation",
            objective: "Manage submittal cycles so procurement, fabrication, and field installation stay aligned to approved intent.",
            prompt: "Construct a submittal decision path for a long-lead package with procurement and installation dependencies.",
            assessment: "Submittal routing simulation",
            linkedSurface: "/portal/projects",
            linkedLabel: "Open Project Flow",
            concepts: ["approval flow", "procurement alignment", "dependency management", "lead-time risk"],
            caseStudy: "A late-resolved submittal freezes procurement and pushes critical-path work without early warning.",
          },
        ],
      },
      {
        key: "closeout-governance",
        code: "CTRL 659",
        title: "Closeout, Turnover, and Warranty Records",
        lessons: 3,
        lab: "Assemble an owner-ready closeout packet and warranty continuity plan.",
        summary: "Connects document governance to revenue protection, turnover quality, and long-term service continuity.",
        linkedSurface: "/portal/audit",
        linkedLabel: "Open Audit",
        lessonsData: [
          {
            key: "closeout-evidence-architecture",
            title: "Closeout Evidence Architecture",
            duration: "95 minutes",
            type: "Seminar",
            objective: "Define the evidence package required for confident owner turnover and payment confidence.",
            prompt: "Design the closeout evidence structure for a multi-trade tenant improvement project.",
            assessment: "Evidence architecture board",
            linkedSurface: "/portal/audit",
            linkedLabel: "Open Audit",
            concepts: ["evidence design", "owner turnover", "completion proof", "payment protection"],
            caseStudy: "Final payment stalls because closeout content arrives as an unstructured file dump.",
          },
          {
            key: "warranty-record-continuity",
            title: "Warranty Record Continuity",
            duration: "85 minutes",
            type: "Applied Lab",
            objective: "Preserve the data and files required to respond intelligently during warranty and recurring service phases.",
            prompt: "Translate closeout records into a warranty-ready operating index.",
            assessment: "Warranty continuity packet",
            linkedSurface: "/warranty",
            linkedLabel: "Open Warranty lane",
            concepts: ["service continuity", "record transfer", "asset traceability", "post-construction trust"],
            caseStudy: "A client reports a system issue months later and the contractor cannot quickly locate final approved documents.",
          },
          {
            key: "audit-ready-close",
            title: "Audit-Ready Project Close",
            duration: "110 minutes",
            type: "Capstone Review",
            objective: "Close a project with full auditability across files, communications, approvals, and next-service obligations.",
            prompt: "Present a final project close package to an internal governance panel.",
            assessment: "Capstone panel review",
            linkedSurface: "/portal/support",
            linkedLabel: "Open Support Continuity",
            concepts: ["close discipline", "audit readiness", "handoff to service", "organizational memory"],
            caseStudy: "The project is physically complete but commercially exposed because turnover proof is incomplete.",
          },
        ],
      },
    ],
  },
  {
    key: "field-readiness",
    title: "Field Safety and Mobilization Readiness",
    credential: "Field Readiness Badge",
    audience: "Superintendents, foremen, crew leads, safety coordinators, and field onboarding cohorts",
    duration: "8 weeks · field leadership seminar + mobilization drill series",
    format: "Safety drills, field simulation, kickoff planning, supervisor coaching, daily log discipline",
    outcome: "Prepare crews for mobilization, job hazard analysis, toolbox talks, and escalation discipline.",
    goal: "Unite safety, field control, and operational professionalism into one mobilization-ready standard.",
    linkedSurface: "/portal/support",
    linkedLabel: "Open Support Continuity",
    classrooms: ["Field Safety, Mobilization, and Readiness"],
    stack: ["Support continuity", "Safety refreshers", "Kickoff readiness", "Crew communications"],
    outcomes: [
      "Lead mobilization with documented readiness instead of verbal optimism.",
      "Convert hazard analysis into site behavior, supervision, and escalation practice.",
      "Use daily documentation to protect field truth and management response quality.",
      "Bridge classroom discipline to live project kickoff, communications, and corrective action.",
    ],
    courses: [
      {
        key: "mobilization-command",
        code: "FIELD 612",
        title: "Mobilization Command and Site Readiness",
        lessons: 3,
        lab: "Conduct a site-start readiness review with safety, logistics, and document alignment checks.",
        summary: "Develops leadership capability for safe, orderly, well-documented job starts.",
        linkedSurface: "/portal/support",
        linkedLabel: "Open Support Continuity",
        lessonsData: [
          {
            key: "mobilization-logic",
            title: "Mobilization Logic and Readiness Gates",
            duration: "95 minutes",
            type: "Seminar",
            objective: "Define the conditions that must be satisfied before a crew should start work.",
            prompt: "Create a mobilization gate list covering drawings, permits, safety controls, manpower, and site logistics.",
            assessment: "Readiness gate checklist",
            linkedSurface: "/portal/projects",
            linkedLabel: "Open Project Flow",
            concepts: ["readiness gates", "permit awareness", "crew planning", "site logistics"],
            caseStudy: "A crew is sent to a site without clarified access, current drawings, or a controlled work plan.",
          },
          {
            key: "jha-leadership",
            title: "JHA Leadership and Hazard Anticipation",
            duration: "100 minutes",
            type: "Field Lab",
            objective: "Lead job hazard analysis as a predictive supervision tool rather than a compliance formality.",
            prompt: "Run a JHA for a complex mobilization sequence involving multiple trades and changing site conditions.",
            assessment: "JHA facilitation rubric",
            linkedSurface: "/portal/support",
            linkedLabel: "Open Support Continuity",
            concepts: ["hazard anticipation", "crew leadership", "control measures", "pre-task planning"],
            caseStudy: "A crew repeats routine work but misses a changed overhead condition that materially alters risk.",
          },
          {
            key: "toolbox-talk-design",
            title: "Toolbox Talk Design for Real Retention",
            duration: "80 minutes",
            type: "Workshop",
            objective: "Build toolbox talks that actually influence crew behavior and retention.",
            prompt: "Design and deliver a toolbox talk tied to a current mobilization risk and field observation trend.",
            assessment: "Toolbox talk delivery score",
            linkedSurface: "/portal/messages",
            linkedLabel: "Open crew communications",
            concepts: ["adult learning", "crew engagement", "field communication", "behavior reinforcement"],
            caseStudy: "Crews tune out repetitive safety talks because the content is generic, detached, and not site-specific.",
          },
        ],
      },
      {
        key: "field-documentation",
        code: "FIELD 638",
        title: "Daily Logs, Escalation, and Field Evidence",
        lessons: 3,
        lab: "Produce a field event log and escalation packet linked to project controls.",
        summary: "Teaches superintendents and foremen how to turn daily events into high-quality operational evidence.",
        linkedSurface: "/portal/audit",
        linkedLabel: "Open Audit",
        lessonsData: [
          {
            key: "daily-log-discipline",
            title: "Daily Log Discipline",
            duration: "85 minutes",
            type: "Applied Lab",
            objective: "Capture manpower, weather, safety, site events, and blockers with enough clarity to support real management action.",
            prompt: "Rewrite a weak superintendent daily report into an executive-usable field log.",
            assessment: "Field log audit",
            linkedSurface: "/portal/audit",
            linkedLabel: "Open Audit",
            concepts: ["field evidence", "signal density", "management usability", "documentation credibility"],
            caseStudy: "Leadership receives daily reports but still cannot understand what is actually happening on site.",
          },
          {
            key: "field-escalation-sequencing",
            title: "Field Escalation Sequencing",
            duration: "90 minutes",
            type: "Simulation",
            objective: "Escalate field issues in the correct order with the right facts, stakeholders, and documented requests.",
            prompt: "Sequence an escalation for a safety concern, missing material, and conflicting drawing condition occurring on the same day.",
            assessment: "Escalation simulation",
            linkedSurface: "/portal/messages",
            linkedLabel: "Open Messages",
            concepts: ["escalation timing", "fact packaging", "stakeholder routing", "response discipline"],
            caseStudy: "A solvable issue becomes a major disruption because the field team escalates late and without evidence.",
          },
          {
            key: "field-to-closeout",
            title: "From Field Evidence to Closeout Confidence",
            duration: "100 minutes",
            type: "Synthesis Review",
            objective: "Demonstrate how disciplined field records improve pay applications, closeout readiness, and warranty response.",
            prompt: "Trace the connection between daily logs, issue tracking, closeout records, and future service confidence.",
            assessment: "Synthesis presentation",
            linkedSurface: "/portal/billing",
            linkedLabel: "Open Billing",
            concepts: ["evidence chain", "billing support", "closeout linkage", "warranty continuity"],
            caseStudy: "The contractor completed the work but lacks the record quality needed to defend progress, completion, and service history.",
          },
        ],
      },
    ],
  },
];

const { programsByKey, coursesByKey, lessonsByKey } = buildCatalogIndex(programs);

export function getProgramByKey(programKey) {
  return programsByKey.get(programKey) || null;
}

export function getCourseByKey(programKey, courseKey) {
  return coursesByKey.get(`${programKey}:${courseKey}`) || null;
}

export function getLessonByKey(programKey, courseKey, lessonKey) {
  return lessonsByKey.get(`${programKey}:${courseKey}:${lessonKey}`) || null;
}

export const academyCatalog = {
  programs,
  credentials: programs.map((program) => ({
    title: program.credential,
    renewal: program.key === "field-readiness" ? "Mobilization-ready safety verification every 6 months" : "Annual or semi-annual faculty review and operating-practice recalibration",
    evidence: `${program.title} seminar work, applied labs, and capstone-quality operating evidence.`,
  })),
  pathways: programs.map((program) => ({
    title: `${program.title} pathway`,
    description: program.goal,
    route: buildProgramHref(program.key),
    label: `Open ${program.title}`,
  })),
};
