export const academyCatalog = {
  programs: [
    {
      key: "operations-foundations",
      title: "Construction Operations Foundations",
      credential: "FCA Core Operations Certificate",
      audience: "Owners, office managers, coordinators, and new team leads",
      duration: "4 weeks",
      format: "Guided cohort + on-demand lessons + workspace lab",
      goal: "Build baseline fluency in how FCA carries a contractor from intake through production, customer visibility, and follow-through.",
      outcomes: [
        "Navigate FCA public, portal, and academy surfaces with real workspace context",
        "Understand project lifecycle state from opportunity through closeout",
        "Use Auricrux guidance to identify blockers and next actions",
        "Coordinate office-to-field continuity using shared customer and project state",
      ],
      courses: [
        {
          code: "OPS-101",
          title: "Workspace Orientation and Contractor Lifecycle",
          lessons: 6,
          lab: "Portal orientation lab",
        },
        {
          code: "OPS-115",
          title: "Lead Intake, Discovery, and Qualification Discipline",
          lessons: 5,
          lab: "Opportunity review scenario",
        },
        {
          code: "OPS-130",
          title: "Project Setup, Roles, and Delivery Continuity",
          lessons: 6,
          lab: "Tenant-to-project handoff exercise",
        },
      ],
      linkedSurface: "/portal/platform",
      linkedLabel: "Open Platform Dashboard",
    },
    {
      key: "estimating-margin-control",
      title: "Estimating, Bidding, and Margin Control",
      credential: "Preconstruction Readiness Certificate",
      audience: "Estimators, project executives, and preconstruction managers",
      duration: "6 modules",
      format: "Estimator lab + vendor scenario drills",
      goal: "Give FCA teams a real bid pathway tied to takeoff discipline, vendor coordination, approvals, and margin protection.",
      outcomes: [
        "Assemble bid packages with traceable scope boundaries",
        "Compare vendors and alternates with clearer award logic",
        "Protect contingency and margin through change forecasting",
        "Carry awarded work into project kickoff without context loss",
      ],
      courses: [
        {
          code: "EST-201",
          title: "Scope Decomposition and Bid Packaging",
          lessons: 5,
          lab: "Bid package assembly lab",
        },
        {
          code: "EST-225",
          title: "Takeoff Discipline and Pricing Structure",
          lessons: 6,
          lab: "Quantity and pricing worksheet exercise",
        },
        {
          code: "EST-245",
          title: "Vendor Leveling and Margin Protection",
          lessons: 5,
          lab: "Vendor comparison scenario",
        },
      ],
      linkedSurface: "/portal/bids",
      linkedLabel: "Open Bid Workspace",
    },
    {
      key: "document-control",
      title: "Document Control, RFIs, and Submittals",
      credential: "Project Controls Certificate",
      audience: "Project managers, coordinators, and document controllers",
      duration: "5-part technical lab",
      format: "Interactive file review + communications simulation",
      goal: "Train teams to manage drawing sets, RFIs, submittals, and closeout packages as a coordinated operating discipline.",
      outcomes: [
        "Track revisions and file dependencies without route drift",
        "Draft RFIs with clearer turnaround expectations",
        "Move submittals through approvals with visible dependencies",
        "Prepare closeout packages in a reusable digital structure",
      ],
      courses: [
        {
          code: "DOC-301",
          title: "Drawing Logs and Revision Control",
          lessons: 5,
          lab: "Drawing register exercise",
        },
        {
          code: "DOC-325",
          title: "RFI Workflow and Turnaround Discipline",
          lessons: 4,
          lab: "RFI drafting lab",
        },
        {
          code: "DOC-350",
          title: "Submittals, Approvals, and Closeout Readiness",
          lessons: 6,
          lab: "Closeout package planning exercise",
        },
      ],
      linkedSurface: "/portal/files",
      linkedLabel: "Open Files Workspace",
    },
    {
      key: "field-readiness",
      title: "Field Safety, Mobilization, and Readiness",
      credential: "Field Readiness Badge",
      audience: "Superintendents, field leads, apprentices, and mobilization coordinators",
      duration: "3-week mobilization sprint",
      format: "Safety drills + kickoff planning + supervisor coaching",
      goal: "Connect startup safety, mobilization readiness, and escalation lanes to the same production system customers already rely on.",
      outcomes: [
        "Execute startup safety checks before mobilization",
        "Run toolbox talks and orientation with repeatable discipline",
        "Escalate field blockers through the correct comms lanes",
        "Keep field readiness tied to customer delivery expectations",
      ],
      courses: [
        {
          code: "FLD-401",
          title: "Job Hazard Analysis and Startup Checklists",
          lessons: 4,
          lab: "Site startup review",
        },
        {
          code: "FLD-420",
          title: "Orientation, Toolbox Talks, and Incident Reporting",
          lessons: 5,
          lab: "Supervisor coaching scenario",
        },
        {
          code: "FLD-445",
          title: "Mobilization Coordination and Escalation Lanes",
          lessons: 4,
          lab: "Field kickoff planning workshop",
        },
      ],
      linkedSurface: "/portal/support",
      linkedLabel: "Open Support Continuity",
    },
  ],
};
