const FORMAT_GROUPS = {
  cad: ["dwg", "dxf", "dgn"],
  bim: ["rvt", "ifc", "nwd", "nwc", "nwf", "skp"],
  documentation: ["pdf", "tiff", "cals", "dwf"],
  collaboration: ["bcf", "cobie", "step", "stp"],
  visual: ["jpg", "jpeg", "png"],
};

export const FCA_MINIMUM_INPUT_FORMATS = [
  ...FORMAT_GROUPS.cad,
  ...FORMAT_GROUPS.bim,
  ...FORMAT_GROUPS.documentation,
  ...FORMAT_GROUPS.collaboration,
  ...FORMAT_GROUPS.visual,
];

export const FCA_MINIMUM_OUTPUT_FORMATS = [
  ...FCA_MINIMUM_INPUT_FORMATS,
  "json",
  "csv",
  "txt",
];

export const FCA_MINIMUM_OUTPUT_FORMAT_OPTIONS = FCA_MINIMUM_OUTPUT_FORMATS.map((format) => ({
  value: format,
  label: format.toUpperCase(),
}));

export function toAcceptAttribute(formats = FCA_MINIMUM_INPUT_FORMATS) {
  return formats.map((format) => `.${format}`).join(",");
}

export function normalizeFormat(value = "") {
  return String(value || "").toLowerCase().replace(/[^a-z0-9]/g, "").trim();
}

export function inferFormatFromName(name = "") {
  const normalized = String(name || "").toLowerCase();
  const segments = normalized.split(".");
  if (segments.length < 2) return "";
  return normalizeFormat(segments.pop());
}

export function isConstructionDesignFile(file = {}) {
  const fromFormat = normalizeFormat(file.format || "");
  const fromName = inferFormatFromName(file.name || "");
  const candidate = fromFormat || fromName;
  return Boolean(file.designReady || FCA_MINIMUM_INPUT_FORMATS.includes(candidate));
}

function escapeCsv(value) {
  const raw = String(value ?? "");
  if (raw.includes(",") || raw.includes("\"") || raw.includes("\n")) {
    return `\"${raw.replace(/\"/g, "\"\"")}\"`;
  }
  return raw;
}

function asCsvRows(rows = []) {
  return rows.map((row) => row.map((value) => escapeCsv(value)).join(",")).join("\n");
}

function asBcfXml(payload = {}) {
  const title = payload.packageName || payload.title || "FCA Issue";
  const description = payload.description || "Governed issue package generated by FCA native workflow.";
  return [
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
    "<Markup>",
    "  <Header>",
    `    <File IfcProject=\"${payload.projectId || ""}\" />`,
    "  </Header>",
    "  <Topic>",
    `    <Title>${title}</Title>`,
    `    <Description>${description}</Description>`,
    "  </Topic>",
    "</Markup>",
  ].join("\n");
}

function asCobieCsv(payload = {}) {
  const projectId = payload.projectId || "";
  const rows = [
    ["SheetName", "Name", "CreatedBy", "CreatedOn", "Category", "Description", "ExtSystem", "ExtObject"],
    ["Facility", projectId, "FCA", payload.generatedAt || new Date().toISOString(), "Project", payload.packageName || "Plan Package", "FCA", "Project"],
  ];
  (payload.files || []).forEach((file, index) => {
    rows.push([
      "Document",
      file.name || `File-${index + 1}`,
      "FCA",
      payload.generatedAt || new Date().toISOString(),
      file.category || "Document",
      file.discipline || "General",
      "FCA",
      file.fileId || "",
    ]);
  });
  return asCsvRows(rows);
}

function buildGenericContent(format, payload = {}) {
  const lines = [
    `FCA Native Package (${String(format || "").toUpperCase()})`,
    "Hosted on Microsoft-native FCA resources",
    `Project: ${payload.projectId || ""}`,
    `Package: ${payload.packageName || ""}`,
    `Generated: ${payload.generatedAt || new Date().toISOString()}`,
    "",
    "Files:",
    ...(payload.files || []).map((file, index) => `${index + 1}. ${file.name || "Unnamed"} [${file.discipline || "General"}]`),
  ];
  return lines.join("\n");
}

export function buildStructuredExport({ format, payload, baseName }) {
  const normalizedFormat = normalizeFormat(format || "json") || "json";
  const safeBaseName = String(baseName || "fca-package").replace(/[^a-zA-Z0-9_-]+/g, "-").toLowerCase();

  if (normalizedFormat === "json") {
    return {
      fileName: `${safeBaseName}.json`,
      mimeType: "application/json",
      content: JSON.stringify(payload, null, 2),
    };
  }

  if (normalizedFormat === "csv") {
    const rows = [
      ["projectId", "packageName", "fileId", "name", "category", "discipline", "status", "generatedAt"],
      ...((payload.files || []).map((file) => [
        payload.projectId || "",
        payload.packageName || "",
        file.fileId || "",
        file.name || "",
        file.category || "",
        file.discipline || "",
        file.status || "",
        payload.generatedAt || "",
      ])),
    ];

    return {
      fileName: `${safeBaseName}.csv`,
      mimeType: "text/csv",
      content: asCsvRows(rows),
    };
  }

  if (normalizedFormat === "txt") {
    return {
      fileName: `${safeBaseName}.txt`,
      mimeType: "text/plain",
      content: buildGenericContent("txt", payload),
    };
  }

  if (normalizedFormat === "bcf") {
    return {
      fileName: `${safeBaseName}.bcf`,
      mimeType: "application/xml",
      content: asBcfXml(payload),
    };
  }

  if (normalizedFormat === "cobie") {
    return {
      fileName: `${safeBaseName}.cobie.csv`,
      mimeType: "text/csv",
      content: asCobieCsv(payload),
    };
  }

  if (normalizedFormat === "jpg" || normalizedFormat === "jpeg" || normalizedFormat === "png") {
    return {
      fileName: `${safeBaseName}.${normalizedFormat === "jpeg" ? "jpg" : normalizedFormat}`,
      mimeType: "text/plain",
      content: buildGenericContent(normalizedFormat, payload),
    };
  }

  const extension = normalizedFormat;
  return {
    fileName: `${safeBaseName}.${extension}`,
    mimeType: "text/plain",
    content: buildGenericContent(extension, payload),
  };
}
