export const portalTenant = {
  id: "TEN-FCA-001",
  name: "FCA Pilot Customer",
  roleSummary: "Owner/Admin workspace with customer portal, billing visibility, and academy continuity enabled.",
};

export const currentProject = {
  id: "PRJ-A117",
  name: "FCA Pilot Customer Tenant Improvement",
  customer: "FCA Pilot Customer",
  stage: "Estimating → Execution Handoff",
  fileSetLabel: "18 linked files and onboarding artifacts",
  fileSpineStatus: "Bid package summary, onboarding roster, and closeout checklist are attached to the same project context.",
  auditLabel: "Auricrux action log active",
  auditStatus: "Customer actions, billing transitions, and academy continuity cues are expected to write into one auditable timeline.",
  auricruxMode: "Context-aware workspace guidance",
  auricruxSummary: "Auricrux is reading the current tenant, project, stage, and next-action state from this shared shell context.",
};

export const workspaceContext = {
  currentStageLabel: "Estimating to execution handoff",
  stageSummary: "The current workspace is positioned between customer approval, operational setup, billing progression, and academy continuity.",
  currentNextAction: "Approve revised scope and release onboarding packet",
  nextActionOwner: "Estimator Team + Customer Success coordination",
  auditStatusLabel: "Shared timeline active",
  auditSummary: "Auricrux, customer-facing actions, and workspace transitions should resolve into one audit spine for PRJ-A117.",
};

export const auricruxRail = {
  systemState: "Auricrux online and context-aware",
  nextRecommendedAction: "Release approval request for Package A-117",
  recommendationReason: "Customer approval is the cleanest path to unlock project setup, file continuity, billing progression, and academy onboarding.",
  currentBlocker: "Open scope approval pending",
  blockerImpact: "Execution handoff, invoice readiness, and workforce assignment stay constrained until the customer decision is recorded.",
  lastAction: "Validated bid completeness and linked onboarding artifacts",
  lastActionResult: "The shared workspace now reflects bid, file, audit, and academy continuity state under PRJ-A117.",
  readinessState: "Workspace active",
  readinessSummary: "Contractor Command connects bids, projects, files, billing, and academy training in one operating workspace.",
};

export const auricruxCommsChannels = [
  {
    label: "Chat",
    value: "Text, video, and audio triage",
    detail: "Auricrux keeps customer, estimator, and field communication inside one live thread so execution context never gets detached from the project spine.",
    href: "/portal/messages",
    ctaLabel: "Open Chat Workspace",
  },
  {
    label: "SMS",
    value: "Approval nudges and field alerts",
    detail: "Use SMS for short-cycle approval follow-through, permit reminders, site readiness, and mobilization cues.",
    href: "/portal/notifications",
    ctaLabel: "Open Alert Stream",
  },
  {
    label: "Phone",
    value: "Escalation and recovery lane",
    detail: "Support and owner escalations stay linked to the same project, billing, and document-control context Auricrux is already tracking.",
    href: "/portal/support",
    ctaLabel: "Open Support Lane",
  },
  {
    label: "Email",
    value: "Commercial and document continuity",
    detail: "Auricrux sequences approval requests, permit release messaging, invoice follow-through, and rollout summaries as part of one executive cadence.",
    href: "/contact",
    ctaLabel: "Open Rollout Path",
  },
  {
    label: "Teams",
    value: "Internal coordination surface",
    detail: "Cross-functional coordination across estimating, project, field, academy, and support is framed as one operating channel rather than isolated team chatter.",
    href: "/portal/platform",
    ctaLabel: "Open Platform Coordination",
  },
  {
    label: "Conference",
    value: "Live review and walkthrough",
    detail: "Live walkthroughs, project reviews, and executive check-ins route directly from the website into the real shell surfaces.",
    href: "/portal/auricrux",
    ctaLabel: "Open Auricrux Guidance",
  },
  {
    label: "Lecture",
    value: "Academy coaching and rollout",
    detail: "Training, onboarding, safety refreshers, and process coaching remain tied to the same customer lifecycle as sales and operations.",
    href: "/academy",
    ctaLabel: "Open Academy",
  },
];

export const routeStateOverlays = {
  platform: {
    title: "Unified platform dashboard state",
    summary: "This route summarizes the whole operating shell in one place so portal operations, academy continuity, support posture, admin readiness, and Auricrux state can be reviewed together.",
    status: "Platform state active",
    primaryFocus: "Executive and customer summary",
    primaryDetail: "This route is the clearest single-surface view of current tenant, project, readiness, and operating continuity.",
    dependency: "Shared route-state integrity",
    dependencyDetail: "The platform view depends on all specialized routes staying attached to the same tenant, project, file, audit, and Auricrux state.",
    auricruxRole: "Summarize and direct",
    auricruxDetail: "Auricrux uses this route to present system state clearly and direct the user into the next operational surface.",
  },
  overview: {
    title: "Workspace overview state",
    summary: "Overview emphasizes account-level continuity, active next actions, and readiness to move the customer into deeper operational routes.",
    status: "Overview active",
    primaryFocus: "Cross-route visibility",
    primaryDetail: "This route summarizes the shared tenant, project, and Auricrux state before deeper operational handling.",
    dependency: "Project and messaging continuity",
    dependencyDetail: "Overview depends on project context, message activity, and next-action sequencing staying aligned.",
    auricruxRole: "Sequence and explain",
    auricruxDetail: "Auricrux surfaces current priorities and explains what route should be opened next.",
  },
  bids: {
    title: "Bid route state",
    summary: "Bids specialize the shared workspace state around approval readiness, estimating blockers, and conversion into project setup.",
    status: "Bid state active",
    primaryFocus: "Approval progression",
    primaryDetail: "This route focuses on the decision path that turns estimating work into a true project record.",
    dependency: "Customer scope approval",
    dependencyDetail: "Until scope approval is recorded, downstream project, billing, and academy actions remain constrained.",
    auricruxRole: "Validate and recommend",
    auricruxDetail: "Auricrux checks bid completeness, explains blockers, and recommends the next approval move.",
  },
  projects: {
    title: "Project route state",
    summary: "Projects specialize the shared state around delivery coordination, stage ownership, and execution handoff readiness.",
    status: "Project state active",
    primaryFocus: "Operational handoff",
    primaryDetail: "This route anchors execution continuity and makes the project/job record the operational root.",
    dependency: "Bid-to-project conversion",
    dependencyDetail: "Project operations depend on approved bid state and clean linkage into the shared project object.",
    auricruxRole: "Track and correct",
    auricruxDetail: "Auricrux monitors stage movement, identifies missing handoff information, and preserves accountability.",
  },
  files: {
    title: "File route state",
    summary: "Files specialize the shared state around artifact linkage, project evidence continuity, and usable document access.",
    status: "File state active",
    primaryFocus: "Artifact attachment",
    primaryDetail: "This route ensures bid packages, onboarding documents, and project artifacts remain attached to one project spine.",
    dependency: "Project-linked file spine",
    dependencyDetail: "File handling depends on shared project identity and auditable attachment of documents to operational records.",
    auricruxRole: "Read and contextualize",
    auricruxDetail: "Auricrux reads file context, explains what each artifact means, and detects documentation gaps.",
  },
  legal: {
    title: "Contractor legal command state",
    summary: "Legal specializes entity formation, Virginia licensure, agreements, lien waivers, insurance COIs, and compliance checklist continuity.",
    status: "Legal workspace active",
    primaryFocus: "Compliance readiness",
    primaryDetail: "This route tracks licenses, executed agreements, waiver discipline, and formation checklist before customer delivery.",
    dependency: "File spine and billing linkage",
    dependencyDetail: "Legal execution depends on storing executed documents on the file spine and aligning lien waivers with billing events.",
    auricruxRole: "Detect gaps and recommend",
    auricruxDetail: "Auricrux flags missing DPOR, insurance, or contract steps and routes learners to Academy legal tracks.",
  },
  design: {
    title: "Design Workspace route state",
    summary: "Design Workspace unifies PDF, DWG, and RVT viewing with shared markup, takeoff, and coordination continuity.",
    status: "Design session active",
    primaryFocus: "Plan review and markup",
    primaryDetail: "This route anchors governed plan sets, sheet navigation, markup layers, and takeoff linkage in one enterprise workspace.",
    dependency: "Binary file spine and sheet manifest",
    dependencyDetail: "Design Workspace depends on blob-backed file artifacts, extraction manifests, and project linkage.",
    auricruxRole: "Explain, recommend, and act",
    auricruxDetail: "Auricrux reads active sheets and markups, explains revision changes, recommends takeoff gaps, and can spawn RFIs or takeoffs.",
  },
  messages: {
    title: "Message route state",
    summary: "Messages specialize the shared state around communication continuity, escalation awareness, and customer movement to the next step.",
    status: "Message state active",
    primaryFocus: "Communication follow-through",
    primaryDetail: "This route keeps customer-facing and internal communication from becoming a dead-end surface.",
    dependency: "Shared audit and next-action state",
    dependencyDetail: "Messages depend on knowing what was last done, what is pending, and who owns the next step.",
    auricruxRole: "Escalate and clarify",
    auricruxDetail: "Auricrux uses message state to explain urgency, preserve continuity, and route the customer forward.",
  },
  notifications: {
    title: "Notification route state",
    summary: "Notifications specialize the shared state around alert visibility, recent activity awareness, and continuity cues tied to the same customer workspace.",
    status: "Notification state active",
    primaryFocus: "Alert visibility",
    primaryDetail: "This route centralizes what changed most recently so the customer can react without losing project and Auricrux context.",
    dependency: "Message, audit, and route continuity",
    dependencyDetail: "Notifications depend on message activity, audit events, and shared route-state continuity remaining attached to the same customer and project spine.",
    auricruxRole: "Signal and prioritize",
    auricruxDetail: "Auricrux turns recent messages and audit events into a prioritized alert stream so the customer sees what matters next.",
  },
  billing: {
    title: "Billing route state",
    summary: "Billing specializes the shared state around revenue follow-through, invoice readiness, and customer retention continuity.",
    status: "Billing state active",
    primaryFocus: "Revenue progression",
    primaryDetail: "This route connects approved work to invoice review while keeping academy and long-term support in view.",
    dependency: "Project and audit readiness",
    dependencyDetail: "Billing depends on a clean operational record, linked files, and visible approval history.",
    auricruxRole: "Advance and verify",
    auricruxDetail: "Auricrux checks readiness, flags blockers, and keeps billing from breaking continuity with the rest of the shell.",
  },
  academy: {
    title: "Academy route state",
    summary: "Academy specializes the shared state around workforce enablement, learner readiness, and project-linked training continuity.",
    status: "Academy state active",
    primaryFocus: "Workforce readiness",
    primaryDetail: "This route keeps training, certification, and onboarding connected to the same project and tenant state as the portal.",
    dependency: "Project-linked learner context",
    dependencyDetail: "Academy continuity depends on shared tenant, project, file, and next-action data rather than isolated LMS state.",
    auricruxRole: "Coach and align",
    auricruxDetail: "Auricrux uses operational state to recommend learning actions and align workforce readiness to live work.",
  },
  support: {
    title: "Support route state",
    summary: "Support specializes the shared state around continuity recovery, escalation handling, and customer help inside the same shell.",
    status: "Support state active",
    primaryFocus: "Escalation continuity",
    primaryDetail: "This route keeps support requests attached to project, audit, and next-action context instead of leaving them isolated.",
    dependency: "Message and audit visibility",
    dependencyDetail: "Support depends on current blocker visibility, prior actions, and cross-route context staying available.",
    auricruxRole: "Recover and route",
    auricruxDetail: "Auricrux identifies the cleanest recovery path and sends the user to the next operational surface.",
  },
  admin: {
    title: "Admin route state",
    summary: "Admin specializes the shared state around tenant rollout, seat readiness, governance visibility, and production posture.",
    status: "Admin state active",
    primaryFocus: "Control and rollout",
    primaryDetail: "This route begins the broader platform spine for tenant-level administration inside the same shell.",
    dependency: "Tenant, project, and governance context",
    dependencyDetail: "Admin depends on persistent tenant identity, route continuity, and visible Auricrux governance state.",
    auricruxRole: "Govern and monitor",
    auricruxDetail: "Auricrux keeps administrative state legible and tied to live workspace readiness rather than detached settings.",
  },
  auricrux: {
    title: "Auricrux guidance",
    summary: "Your operator guide for what to do next — blockers, priorities, and the right lane to open.",
    status: "Guidance active",
    primaryFocus: "Next best action",
    primaryDetail: "See what is holding work up and where to go to move it forward.",
    dependency: "Workspace context",
    dependencyDetail: "Guidance works best when your profile, project, and pipeline are set up.",
    auricruxRole: "Guide and explain",
    auricruxDetail: "Ask questions, get step-by-step direction, and jump to the right product.",
  },
};

export const projectAuditEvents = [
  {
    time: "Today · 8:10 AM",
    eventType: "lead-qualified",
    actorType: "auricrux",
    targetObjectType: "Opportunity",
    action: "Auricrux validated bid completeness",
    detail: "Package A-117 was checked for missing scope fields before customer approval routing.",
    reason: "Qualification and pricing continuity must be complete before customer approval is requested.",
    discipline: "Preconstruction",
  },
  {
    time: "Today · 9:25 AM",
    eventType: "file-linked",
    actorType: "user",
    targetObjectType: "FileAsset",
    action: "Permit set and owner exhibit linked",
    detail: "Permit narrative, plan sheet set, and owner exhibit were attached to project PRJ-A117 for shared visibility.",
    reason: "Project-linked evidence is required before submission and downstream coordination.",
    discipline: "Document Control",
  },
  {
    time: "Today · 11:05 AM",
    eventType: "coordination-updated",
    actorType: "workflow",
    targetObjectType: "AuditEvent",
    action: "RFI and submittal register synchronized",
    detail: "The coordination log was updated so field, estimator, and customer teams are reading the same open-document status.",
    reason: "Document-control drift would break execution and trade coordination continuity.",
    discipline: "Coordination",
  },
  {
    time: "Today · 1:40 PM",
    eventType: "training-linked",
    actorType: "auricrux",
    targetObjectType: "TrainingLink",
    action: "Safety onboarding packet prepared",
    detail: "JHA orientation, worker roster, and academy readiness cues were aligned to project PRJ-A117.",
    reason: "Field readiness and academy continuity must remain attached to the same project root.",
    discipline: "Field Readiness",
  },
];

export const portalMetrics = [
  {
    label: "Active Projects",
    value: "4",
    detail: "2 in estimating, 1 in execution, 1 in closeout",
  },
  {
    label: "Unread Messages",
    value: "7",
    detail: "Sales, project coordination, and onboarding updates",
  },
  {
    label: "Documents Ready",
    value: "18",
    detail: "Bids, permits, onboarding forms, and training docs",
  },
  {
    label: "Auricrux Status",
    value: "Online",
    detail: "Monitoring bid status, portal requests, academy handoff, and support escalation",
  },
];

export const portalProjects = [
  {
    id: "A-117",
    customer: "FCA Pilot Customer",
    stage: "Estimating",
    nextAction: "Approve revised scope",
    owner: "Estimator Team",
    due: "Today",
    superintendent: "Pending assignment",
    permitStatus: "Permit set not submitted",
    siteStatus: "Awaiting customer approval before mobilization",
    commercialFocus: "Tenant improvement pricing and long-lead approvals",
  },
  {
    id: "B-204",
    customer: "North Ridge Commercial",
    stage: "Execution",
    nextAction: "Release mobilization checklist",
    owner: "Project Coordinator",
    due: "Tomorrow",
    superintendent: "M. Alvarez",
    permitStatus: "Permit approved",
    siteStatus: "Mobilization scheduled for Monday",
    commercialFocus: "Subcontractor alignment and field kickoff readiness",
  },
  {
    id: "C-332",
    customer: "Cedar Valley Schools",
    stage: "Closeout",
    nextAction: "Collect signed punch confirmation",
    owner: "Customer Success",
    due: "This week",
    superintendent: "R. Carter",
    permitStatus: "Final inspection pending",
    siteStatus: "Punch items down to final owner signoff",
    commercialFocus: "Closeout package and retainage release tracking",
  },
];

export const portalBids = [
  {
    package: "Package A-117",
    value: "$148,000",
    status: "Awaiting Approval",
    blocker: "Customer approval pending",
    estimator: "J. Benton",
    scopePackage: "Interior demo, framing, MEP coordination",
    dueDate: "Today",
    tradeCoverage: "Mechanical quote still provisional",
    nextCommercialMove: "Release revised scope log and owner approval email",
  },
  {
    package: "Package B-204",
    value: "$322,500",
    status: "Quoted",
    blocker: "Need subcontractor pricing refresh",
    estimator: "L. Nguyen",
    scopePackage: "Exterior upgrades and site electrical",
    dueDate: "Monday",
    tradeCoverage: "Electrical and concrete numbers due for final leveling",
    nextCommercialMove: "Close trade leveling sheet and update fee carry",
  },
  {
    package: "Package C-410",
    value: "$96,300",
    status: "Won",
    blocker: "Convert to contract workspace",
    estimator: "A. Ramirez",
    scopePackage: "Finish carpentry and punch completion",
    dueDate: "Contract this week",
    tradeCoverage: "All coverage in hand; move to job-start packet",
    nextCommercialMove: "Issue startup packet, billing schedule, and field onboarding",
  },
];

export const portalFiles = [
  {
    fileId: "FILE-A117-001",
    ownerObjectType: "Project",
    ownerObjectId: "PRJ-A117",
    linkedEvidenceTarget: "Estimate assumptions and owner review packet",
    evidenceStatus: "Evidence linked",
    versionLabel: "Rev 3",
    name: "Bid package summary.pdf",
    category: "Bid",
    updated: "18 minutes ago",
    action: "Review and approve",
    discipline: "Preconstruction",
    status: "Ready for owner review",
    owner: "Estimator Team",
    note: "Scope inclusions, exclusions, and alternates are aligned to Package A-117.",
  },
  {
    fileId: "FILE-A117-002",
    ownerObjectType: "Project",
    ownerObjectId: "PRJ-A117",
    linkedEvidenceTarget: "Permit submission packet",
    evidenceStatus: "Classification ready",
    versionLabel: "Rev 2",
    name: "Permit set_A117.pdf",
    category: "Permit",
    updated: "42 minutes ago",
    action: "Release for submission",
    discipline: "Permitting",
    status: "Awaiting final stamp set",
    owner: "Project Engineer",
    note: "Permit narrative and drawing set are assembled but still waiting on final owner scope approval.",
  },
  {
    fileId: "FILE-A117-003",
    ownerObjectType: "Project",
    ownerObjectId: "PRJ-A117",
    linkedEvidenceTarget: "RFI and submittal register",
    evidenceStatus: "Needs follow-through",
    versionLabel: "Live register",
    name: "RFI_Submittal_Log_A117.xlsx",
    category: "Coordination",
    updated: "1 hour ago",
    action: "Update open items",
    discipline: "Document Control",
    status: "3 open items",
    owner: "Project Coordinator",
    note: "Mechanical coordination item is still holding final trade leveling and long-lead release timing.",
  },
  {
    fileId: "FILE-A117-004",
    ownerObjectType: "Project",
    ownerObjectId: "PRJ-A117",
    linkedEvidenceTarget: "Field onboarding and academy readiness",
    evidenceStatus: "Ready for assignment",
    versionLabel: "Kickoff packet",
    name: "Site_Safety_Onboarding_Packet.pdf",
    category: "Field",
    updated: "2 hours ago",
    action: "Assign field onboarding",
    discipline: "Safety",
    status: "Ready for kickoff",
    owner: "Field Operations",
    note: "JHA orientation, worker sign-off forms, and academy-linked readiness steps are bundled together.",
  },
];

export const portalMessages = [
  {
    from: "Estimator Team",
    subject: "Scope log revised for owner approval",
    preview: "Alternates were tightened, exclusions clarified, and the approval email is ready once mechanical coverage is confirmed.",
    time: "18 min ago",
    channel: "Owner / Estimating",
    priority: "Approval risk",
    nextAction: "Send revised scope log after final trade check",
  },
  {
    from: "Project Coordinator",
    subject: "Permit narrative and drawing set aligned",
    preview: "Permit package is assembled, but the submission hold remains active until the customer signs the revised scope exhibit.",
    time: "34 min ago",
    channel: "Permitting",
    priority: "Document dependency",
    nextAction: "Release permit submission once scope approval lands",
  },
  {
    from: "Field Operations",
    subject: "Safety kickoff packet ready for assignment",
    preview: "JHA orientation, worker roster, and first-day onboarding steps are staged for mobilization once the job start is released.",
    time: "43 min ago",
    channel: "Field Readiness",
    priority: "Mobilization",
    nextAction: "Assign field onboarding to new crew members",
  },
  {
    from: "Auricrux",
    subject: "One approval is holding billing and mobilization",
    preview: "Package A-117 is positioned for approval, and clearing it will unlock permit release, startup packet issuance, and invoice readiness.",
    time: "Now",
    channel: "Executive continuity",
    priority: "System-critical",
    nextAction: "Advance /portal/bids, then /portal/billing",
  },
];

export const portalBilling = [
  {
    invoice: "INV-1042",
    customer: "North Ridge Commercial",
    amount: "$24,800",
    status: "Draft",
    billingBasis: "Schedule of values · Mobilization + rough-in",
    retainage: "10% held",
    aging: "Not submitted",
    owner: "Project Accountant",
    nextAction: "Finalize pay app backup and release for PM review",
  },
  {
    invoice: "INV-1043",
    customer: "Cedar Valley Schools",
    amount: "$11,200",
    status: "Sent",
    billingBasis: "Closeout progress billing",
    retainage: "5% outstanding",
    aging: "12 days open",
    owner: "Customer Success",
    nextAction: "Track owner signoff and retainage release timing",
  },
  {
    invoice: "INV-1044",
    customer: "FCA Pilot Customer",
    amount: "$6,500",
    status: "Ready for review",
    billingBasis: "Preconstruction / startup packet",
    retainage: "No retainage",
    aging: "Pending internal approval",
    owner: "Estimator Team + Accounting",
    nextAction: "Convert scope approval into invoice release",
  },
];

export const auricruxActions = [
  "Review pending customer approval for Bid Package A-117.",
  "Send onboarding packet to 2 newly assigned field users.",
  "Confirm safety certification progress before project mobilization.",
  "Follow up on one open RFI blocking subcontractor pricing.",
];

export const portalModules = [
  {
    href: "/portal/platform",
    label: "Platform",
    description: "Unified executive and customer shell summary",
  },
  {
    href: "/portal",
    label: "Overview",
    description: "Customer account summary and next actions",
  },
  {
    href: "/portal/projects",
    label: "Projects",
    description: "Execution visibility and stage tracking",
  },
  {
    href: "/portal/bids",
    label: "Bids",
    description: "Pipeline, approvals, and conversion readiness",
  },
  {
    href: "/portal/pipeline",
    label: "Commercial Pipeline",
    description: "Guided bid-to-billing workflow in one place",
  },
  {
    href: "/portal/files",
    label: "Files",
    description: "Bid packages, permits, legal docs, and onboarding artifacts",
  },
  {
    href: "/portal/legal",
    label: "Legal",
    description: "Entity, licenses, agreements, lien waivers, and compliance",
  },
  {
    href: "/portal/audit",
    label: "Audit",
    description: "Continuity timeline, evidence linkage, and Auricrux traceability",
  },
  {
    href: "/portal/messages",
    label: "Messages",
    description: "Customer communications and Auricrux updates",
  },
  {
    href: "/portal/notifications",
    label: "Notifications",
    description: "Alert stream for messages, audits, and continuity signals",
  },
  {
    href: "/portal/billing",
    label: "Billing",
    description: "Invoices, review queue, and account follow-through",
  },
  {
    href: "/portal/estimates",
    label: "Estimates",
    description: "Estimate studio, pricing review, and proposal packaging",
  },
  {
    href: "/portal/proposals",
    label: "Proposals",
    description: "Customer-ready proposal handoff and delivery",
  },
  {
    href: "/portal/plans",
    label: "Plans",
    description: "Commercial plan review and upgrade paths",
  },
  {
    href: "/portal/finance",
    label: "Finance",
    description: "Revenue posture, invoicing context, and financial continuity",
  },
  {
    href: "/portal/scheduling",
    label: "Scheduling",
    description: "Mobilization, milestone, and field scheduling",
  },
  {
    href: "/portal/field-tasks",
    label: "Field tasks",
    description: "Customer-visible field work and task execution",
  },
  {
    href: "/portal/field-supervision",
    label: "Field supervision",
    description: "Site photos, plan compare, annotations, and redlines",
  },
  {
    href: "/portal/design",
    label: "Design",
    description: "Design workspace, markups, sheets, and redline continuity",
  },
  {
    href: "/portal/immersive",
    label: "Immersive & VR",
    description: "Field overlay labs, WebXR sessions, and construction simulation",
  },
  {
    href: "/portal/rfis",
    label: "RFIs",
    description: "Requests for information tied to sheets and field conditions",
  },
  {
    href: "/portal/change-orders",
    label: "Change orders",
    description: "Scope changes, pricing, and approval workflow",
  },
  {
    href: "/portal/warranty",
    label: "Warranty",
    description: "Post-handover service, retention, and recurring work",
  },
  {
    href: "/portal/closeout",
    label: "Closeout",
    description: "Turnover binders, artifact tracking, and handoff readiness",
  },
  {
    href: "/portal/auricrux",
    label: "Auricrux",
    description: "Guided next actions and continuity intelligence",
  },
  {
    href: "/portal/profile",
    label: "Profile",
    description: "Account settings, access, and communications preferences",
  },
  {
    href: "/portal/academy",
    label: "Academy",
    description: "Training continuity tied to the same customer journey",
  },
  {
    href: "/portal/support",
    label: "Support",
    description: "Escalation, recovery, and continuity support",
  },
  {
    href: "/portal/admin",
    label: "Admin",
    description: "Tenant control, rollout status, and governance visibility",
  },
];

export const portalJourney = [
  { key: "lead", label: "Lead / Intake", href: "/login" },
  { key: "bid", label: "Bid / Estimate", href: "/portal/bids" },
  { key: "job", label: "Project / Job", href: "/portal/projects" },
  { key: "coordination", label: "Files + Design", href: "/portal/files" },
  { key: "finance", label: "Billing / Admin", href: "/portal/billing" },
  { key: "academy", label: "Academy / Support", href: "/portal/academy" },
];

/** Hub pages show full quick-access grid; only the workspace dashboard uses hub chrome. */
export const portalHubHrefs = ["/portal/platform"];

/** Portal page subtitles must stay concise — max character count for professional UX. */
export const PORTAL_SUBTITLE_MAX = 120;

/** Always-visible portal shortcuts: workspace, products entry, setup, Auricrux. */
export const portalNavPrimary = [
  { label: "Workspace", href: "/portal/platform" },
  { label: "Pipeline", href: "/portal/pipeline" },
  { label: "Projects", href: "/portal/projects" },
  { label: "Files", href: "/portal/files" },
  { label: "Setup", href: "/portal/admin" },
  { label: "Auricrux", href: "/portal/auricrux" },
];

/** Grouped portal navigation for dropdown menus and mobile drawer. */
export const portalNavGroups = [
  {
    label: "Sell and bid",
    items: [
      { label: "Commercial pipeline", href: "/portal/pipeline" },
      { label: "Bids", href: "/portal/bids" },
      { label: "Estimates", href: "/portal/estimates" },
      { label: "Proposals", href: "/portal/proposals" },
    ],
  },
  {
    label: "Deliver",
    items: [
      { label: "Projects", href: "/portal/projects" },
      { label: "Field supervision", href: "/portal/field-supervision" },
      { label: "Scheduling", href: "/portal/scheduling" },
      { label: "Field tasks", href: "/portal/field-tasks" },
      { label: "RFIs", href: "/portal/rfis" },
      { label: "Change orders", href: "/portal/change-orders" },
      { label: "Closeout", href: "/portal/closeout" },
      { label: "Warranty", href: "/portal/warranty" },
    ],
  },
  {
    label: "Office",
    items: [
      { label: "Auricrux", href: "/portal/auricrux" },
      { label: "Files", href: "/portal/files" },
      { label: "Design workspace", href: "/portal/design" },
      { label: "Legal", href: "/portal/legal" },
      { label: "Messages", href: "/portal/messages" },
      { label: "Notifications", href: "/portal/notifications" },
    ],
  },
  {
    label: "Money",
    items: [
      { label: "Finance", href: "/portal/finance" },
      { label: "Billing", href: "/portal/billing" },
      { label: "Plans", href: "/portal/plans" },
    ],
  },
  {
    label: "Training",
    items: [
      { label: "Academy", href: "/portal/academy" },
      { label: "Course catalog", href: "/portal/academy" },
      { label: "Credentials", href: "/portal/academy" },
    ],
  },
  {
    label: "Account",
    items: [
      { label: "Profile", href: "/portal/profile" },
      { label: "Audit", href: "/portal/audit" },
      { label: "Support", href: "/portal/support" },
    ],
  },
];

/** Curated hub tiles on workspace dashboard — full directory via portalModules. */
export const portalHubModules = [
  { href: "/portal/auricrux", label: "Auricrux", description: "What to do next" },
  { href: "/portal/pipeline", label: "Pipeline", description: "Bid through payment" },
  { href: "/portal/bids", label: "Bids", description: "Qualify and award" },
  { href: "/portal/projects", label: "Projects", description: "Job execution" },
  { href: "/portal/field-supervision", label: "Field", description: "Photos and redlines" },
  { href: "/portal/files", label: "Files", description: "Document control" },
  { href: "/portal/billing", label: "Billing", description: "Invoices and collections" },
  { href: "/portal/messages", label: "Messages", description: "Team coordination" },
  { href: "/portal/academy", label: "Academy", description: "Training and certs" },
  { href: "/portal/admin", label: "Setup", description: "Admin and rollout" },
];

export const STORAGE_KEY = "fca_workspace_state_v1";

export const defaultWorkspaceState = {
  tenant: portalTenant,
  project: currentProject,
  workspace: workspaceContext,
  auricrux: auricruxRail,
  meta: {
    backingSource: "workspace",
    persistenceState: "Workspace synchronized",
    lastSyncedAt: null,
  },
};
